services:
  api:
    build: .
    env_file:
      - .env
    restart: always
    command: /app/docker/entrypoint.sh
    ports:
      - "8000:8000"
    networks:
      - inventory-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    env_file:
      - .env
    command: celery -A app.infrastructure.messaging.celery_app.celery_app worker --loglevel=info -Q inventory -E --pool=gevent --concurrency=${CELERY_CONCURRENCY:-10} --prefetch-multiplier=1
    networks:
      - inventory-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    ports:
      - "5432:5432"
    networks:
      - inventory-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - inventory-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  inventory-net:
    driver: bridge
